namespace MyWatchMarketplace.marketplace.Application.DTOs;

public record WatchListingDto(
    string Id,
    string SellerId,
    string SellerName,
    double SellerRating,
    int SellerReviewCount,
    bool SellerVerified,
    string SellerLocation,
    string Brand,
    string Model,
    string ReferenceNumber,
    int Year,
    decimal Price,
    decimal? OriginalPrice,
    string Currency,
    string Condition,
    string Movement,
    string CaseMaterial,
    double CaseDiameter,
    string DialColor,
    string BraceletMaterial,
    string? WaterResistance,
    string? Caliber,
    string? PowerReserve,
    bool HasOriginalBox,
    bool HasOriginalPapers,
    bool? HasServicePapers,
    string? WarrantyUntil,
    List<string> Images,
    string Description,
    string? ProvenanceNotes,
    bool AuthenticityVerified,
    string Status,
    DateTimeOffset CreatedAt,
    int ViewsCount,
    int WishlistCount,
    bool? IsFeatured,
    string? FromPersonalCollectionId
);

public record CreateWatchListingRequest(
    string? SellerId,
    string? SellerName,
    double? SellerRating,
    int? SellerReviewCount,
    bool? SellerVerified,
    string? SellerLocation,
    string Brand,
    string Model,
    string ReferenceNumber,
    int Year,
    decimal Price,
    decimal? OriginalPrice,
    string Currency,
    string Condition,
    string Movement,
    string CaseMaterial,
    double CaseDiameter,
    string DialColor,
    string BraceletMaterial,
    string? WaterResistance,
    string? Caliber,
    string? PowerReserve,
    bool HasOriginalBox,
    bool HasOriginalPapers,
    bool? HasServicePapers,
    string? WarrantyUntil,
    List<string> Images,
    string Description,
    string? ProvenanceNotes,
    bool AuthenticityVerified,
    bool? IsFeatured,
    string? FromPersonalCollectionId
);

public record UpdateWatchListingRequest(
    decimal? Price,
    decimal? OriginalPrice,
    string? Condition,
    string? Description,
    string? ProvenanceNotes,
    List<string>? Images,
    string? Status,
    bool? IsFeatured
);

public record ListingFilterQuery(
    string? Search,
    string? Brand,
    string? Movement,
    string? Condition,
    decimal? MinPrice,
    decimal? MaxPrice,
    bool? HasBox,
    bool? HasPapers,
    string? SortBy
);

