<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MyWatchMarketplace.UserManagement.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\MyWatchMarketplace.SharedKernel\MyWatchMarketplace.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\MyWatchMarketplace.Contracts\MyWatchMarketplace.Contracts.csproj" />
    <ProjectReference Include="..\MyWatchMarketplace.UserManagement.Application\MyWatchMarketplace.UserManagement.Application.csproj" />
    <ProjectReference Include="..\MyWatchMarketplace.UserManagement.Domain\MyWatchMarketplace.UserManagement.Domain.csproj" />
  </ItemGroup>

</Project>
