<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MyWatchMarketplace.CollectorVault.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyWatchMarketplace.CollectorVault.Application\MyWatchMarketplace.CollectorVault.Application.csproj" />
    <ProjectReference Include="..\MyWatchMarketplace.CollectorVault.Infrastructure\MyWatchMarketplace.CollectorVault.Infrastructure.csproj" />
  </ItemGroup>

</Project>

