<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MyWatchMarketplace.SellerHub.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\MyWatchMarketplace.SharedKernel\MyWatchMarketplace.SharedKernel.csproj" />
    <ProjectReference Include="..\MyWatchMarketplace.SellerHub.Application\MyWatchMarketplace.SellerHub.Application.csproj" />
    <ProjectReference Include="..\MyWatchMarketplace.SellerHub.Domain\MyWatchMarketplace.SellerHub.Domain.csproj" />
  </ItemGroup>

</Project>

